---
application:
  name: "make-up-page"
  project: "Project"
  organization: "QoveryCommunity"
routers:
- name: "main-make-up-page"
  routes:
  - application_name: "make-up-page"
    paths:
    - "/*"
